---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rb-<NAME>
subjects:
- kind: ServiceAccount
  name: <NAME>
  namespace: <NAMESPACE>
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: "rbac.authorization.k8s.io"
