apiVersion: v1
kind: Secret
metadata:
  name: tanzu-admin-secret
  namespace: 9204-q-broker
type: Opaque
stringData:
  username: admin
  password: <PASSWORD> # <-------------------------------------------
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: tanzu-admin-user
  namespace: 9204-q-broker
spec:
  tags:
  - administrator # available tags are 'management', 'policymaker', 'monitoring' and 'administrator'
  rabbitmqClusterReference:
    name: broker # rabbitmqCluster must exist in the same namespace as this resource
  importCredentialsSecret:
    name: tanzu-admin-secret
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: tanzu-admin-permission
  namespace: 9204-q-broker
spec:
  vhost: "/"
  user: "admin" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: broker
