apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-non-root
parameters:
  blocksize: "33554432"
  container: MocStorageContainer
  dynamic: "true"
  group: clustergroup-c30q-aks
  hostname: ca-b204d15a-45a0-454e-bb53-ce9fac36422e.snamretegas.priv
  logicalsectorsize: "4096"
  physicalsectorsize: "4096"
  port: "55000"
  fsType: ext4
  directoryPerms: "777"
provisioner: disk.csi.akshci.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true



