---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-imagepull-secret        
  namespace: rabbitmq-system 
type: kubernetes.io/dockerconfigjson  # needs to be this type
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.tanzu.vmware.com": {
          "username": "<EMAIL_VMWARE>",
          "password": "<PASSWORD_VMWARE>",
          "auth": ""
        }
      }
    }    
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tanzu-imagepull-secret
  namespace: rabbitmq-system
spec:
  toNamespaces:
  - "*"  # star means export is available for all namespaces
