#necessario in quanto il server è stato creato in un altro namespace. Da documentazione:
#If creating clusters in a different namespace, you can create a placeholder Secret, and direct the RabbitmqCluster to use it:
#Since we earlier created a SecretExport object, this placeholder secret will be autopopulated by secretgen-controller, and the RabbitmqCluster will be able to authenticate to the registry using this Secret.
---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-imagepull-secret 
  namespace: 9204-q-broker
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
