---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-<NAME>
# The namespace of the RoleBinding determines where the permissions are granted.
# This only grants permissions within the "development" namespace.
  namespace: <NAMESPACE>
subjects:
- kind: ServiceAccount
  name: <NAME>
  namespace: <NAMESPACE>
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: "rbac.authorization.k8s.io"
