apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: EditAccessNamespace
  namespace: 1750-d-tdtr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: User
  name: devuser
  namespace: 1750-d-tdtr
