apiVersion: v1
kind: Service
metadata:
  name: {{ include "connected-registry.service-name" . }}
  namespace: {{ include "connected-registry.namespace" . }}
  labels: 
    {{- include "connected-registry.labels" . | nindent 4 }}
  annotations:
    description: {{ .Chart.Description }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 8080
    {{- if not .Values.httpEnabled }}
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: 8443
    {{- end }}
  selector:
    {{- include "connected-registry.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP | quote }}
  {{- end }}