{{- if and (not .Values.httpEnabled) (eq (include "connected-registry.tlsType" .) "certificateKeyPair") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connected-registry.tls-secret-name" . }}
  namespace: {{ include "connected-registry.namespace" . }}
  labels: 
    {{- include "connected-registry.labels" . | nindent 4 }}
  annotations:
    description: {{ .Chart.Description }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | quote }}
  tls.key: {{ .Values.tls.key | quote }}
{{- end }}