apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
  namespace: pod-test-2
spec:
  storageClassName: default-non-root
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
