apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-role-binding
# The namespace of the RoleBinding determines where the permissions are granted.
# This only grants permissions within the "development" namespace.
  namespace: <namespace-name>
subjects:
- kind: ServiceAccount
  name: <serviceaccount-name>
  namespace: <namespace-name>
roleRef:
  kind: Role
  name: edit-role
  apiGroup: "rbac.authorization.k8s.io"
