---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-operator
  namespace: default
---
#ruolo a livello di cluster creato per permettere l'installazione temporanea di tanzu
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installation-tanzu-clusterrole
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: installation-tanzu-clusterolebinding
subjects:
- kind: ServiceAccount
  name: tanzu-operator
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: installation-tanzu-clusterrole
  apiGroup: rbac.authorization.k8s.io
