apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: "connected-registry"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: "connected-registry"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "connected-registry"
    spec:
      containers:
       - name: hello-world
         image: 10.96.0.82:443/acc/samples/helloworld:latest
      imagePullSecrets:
       - name: regcred
